### ISSUE TITLE
请求授权豁免

### ISSUE THREAD

**Issue by yangjun1994** [OpenEStimCtrl/.github#1]
作者你好，
我未来准备做一些智能产品，希望在我的产品中用到本项目中的部分源码，现请求商用授权。
同时，我现在使用的某第三方库由于使用了您的库，受到AGPL影响，因此我请求一个授权豁免。

如需写公司/工作室名，可以连接到我的github。
-YangJun

**Comment by sound-reload** [comment]
已登记您的授权，感谢您的使用。
如果有已开发的产品请在下方留言添加，谢谢！
